
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
            args: [--allow-multiple-documents]
        -   id: check-case-conflict
        -   id: debug-statements
        -   id: detect-private-key
        -   id: check-merge-conflict
        -   id: check-added-large-files
            args: ['--maxkb=5000']
    -   repo: https://github.com/myint/autoflake
        rev: v2.2.0
        hooks:
        -   id: autoflake
            args:
              - --in-place
              - --remove-duplicate-keys
              - --remove-unused-variables
              - --remove-all-unused-imports
              - --expand-star-imports
    -   repo: https://github.com/PyCQA/isort
        rev: 5.12.0
        hooks:
        -   id: isort
            args:
              - --profile
              - black
    -   repo: https://github.com/ambv/black
        rev: 23.7.0
        hooks:
        -   id: black
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v1.5.0'  # Use the sha / tag you want to point at
        hooks:
        -   id: mypy
            args:
              - --ignore-missing-imports
              - --install-types
              - --non-interactive
